"""add bookmarks table

Revision ID: 788ac94a8323
Revises: add_qf_oauth_fields_to_users
Create Date: 2026-05-19 17:49:39.129853+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "788ac94a8323"
down_revision: str | Sequence[str] | None = "add_qf_oauth_fields_to_users"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "topics",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("canonical_query", sa.String(length=255), nullable=False),
        sa.Column("embedding", sa.Text(), nullable=True),
        sa.Column("search_count", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("step", sa.String(length=200), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topics_canonical_query"), "topics", ["canonical_query"], unique=True
    )
    op.create_index(op.f("ix_topics_slug"), "topics", ["slug"], unique=True)
    op.create_index(op.f("ix_topics_status"), "topics", ["status"], unique=False)
    op.create_table(
        "topic_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("ayah_key", sa.String(length=20), nullable=False),
        sa.Column("surah_name", sa.String(length=100), nullable=False),
        sa.Column("arabic_text", sa.Text(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("why_this_verse", sa.Text(), nullable=True),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("relevance_score", sa.Float(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("tafsir_excerpt", sa.Text(), nullable=True),
        sa.Column("tafsir_author", sa.String(length=255), nullable=True),
        sa.Column("tafsir_edition", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_topic_results_topic_id"), "topic_results", ["topic_id"], unique=False
    )
    op.create_table(
        "user_searches",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("topic_id", sa.UUID(), nullable=False),
        sa.Column("user_query", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["topic_id"], ["topics.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_user_searches_topic_id"), "user_searches", ["topic_id"], unique=False
    )
    op.drop_table("profiles")
    op.drop_index(op.f("ix_searches_slug"), table_name="searches")
    op.drop_index(op.f("ix_searches_status"), table_name="searches")
    op.drop_table("searches")
    op.add_column("bookmarks", sa.Column("surah_number", sa.Integer(), nullable=False))
    op.add_column("bookmarks", sa.Column("verse_number", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "bookmarks", "users", ["user_id"], ["id"])
    op.drop_column("bookmarks", "note")
    op.drop_column("bookmarks", "extra_data")
    op.drop_column("bookmarks", "translation")
    op.drop_column("bookmarks", "arabic_text")
    op.drop_column("bookmarks", "surah_name")
    op.drop_index(op.f("ix_notes_user_id"), table_name="notes")
    op.create_foreign_key(
        None, "notes", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "users",
        sa.Column(
            "preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
    )
    op.add_column("users", sa.Column("qf_sub", sa.String(length=255), nullable=True))
    op.add_column(
        "users", sa.Column("qf_refresh_token", sa.String(length=512), nullable=True)
    )
    op.add_column(
        "users", sa.Column("qf_id_token", sa.String(length=2048), nullable=True)
    )
    op.create_unique_constraint(None, "users", ["qf_sub"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "qf_id_token")
    op.drop_column("users", "qf_refresh_token")
    op.drop_column("users", "qf_sub")
    op.drop_column("users", "preferences")
    op.drop_constraint(None, "notes", type_="foreignkey")
    op.create_index(op.f("ix_notes_user_id"), "notes", ["user_id"], unique=False)
    op.add_column(
        "bookmarks",
        sa.Column(
            "surah_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "bookmarks",
        sa.Column("arabic_text", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookmarks",
        sa.Column("translation", sa.TEXT(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "bookmarks",
        sa.Column(
            "extra_data",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "bookmarks", sa.Column("note", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "bookmarks", type_="foreignkey")
    op.drop_column("bookmarks", "verse_number")
    op.drop_column("bookmarks", "surah_number")
    op.create_table(
        "searches",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("slug", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("topic", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("status", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.Column("step", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "raw_results",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "results",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "session_id", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("searches_user_id_fkey"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("searches_pkey")),
        sa.UniqueConstraint(
            "slug",
            name=op.f("searches_slug_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(op.f("ix_searches_status"), "searches", ["status"], unique=False)
    op.create_index(op.f("ix_searches_slug"), "searches", ["slug"], unique=True)
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "headline", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("summary", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("phone", sa.VARCHAR(length=50), autoincrement=False, nullable=True),
        sa.Column(
            "location", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "linkedin_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "github_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "portfolio_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("profiles_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profiles_pkey")),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("profiles_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_index(op.f("ix_user_searches_topic_id"), table_name="user_searches")
    op.drop_table("user_searches")
    op.drop_index(op.f("ix_topic_results_topic_id"), table_name="topic_results")
    op.drop_table("topic_results")
    op.drop_index(op.f("ix_topics_status"), table_name="topics")
    op.drop_index(op.f("ix_topics_slug"), table_name="topics")
    op.drop_index(op.f("ix_topics_canonical_query"), table_name="topics")
    op.drop_table("topics")
    # ### end Alembic commands ###
